CLASS zcl_33_record_alg DEFINITION
  PUBLIC
  INHERITING FROM zcl_32_constr_contract_alg
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_33_RECORD_ALG IMPLEMENTATION.
ENDCLASS.
