CLASS zcl_19_honda_alg DEFINITION ABSTRACT INHERITING FROM zcl_18_moto_alg
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    METHODS set_model ABSTRACT EXPORTING model TYPE string.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_19_HONDA_ALG IMPLEMENTATION.
ENDCLASS.
