CLASS zcl_07_animal_alg DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk RETURNING VALUE(rv_walk) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_07_ANIMAL_ALG IMPLEMENTATION.


  METHOD walk.
    rv_walk = 'The animal walks'.
  ENDMETHOD.
ENDCLASS.
