CLASS zcl_16_sales_department_alg DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES zif_05_sales_order_alg.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_16_SALES_DEPARTMENT_ALG IMPLEMENTATION.


  METHOD zif_04_document_alg~set_sales_doc.

  ENDMETHOD.


  METHOD zif_05_sales_order_alg~create_order.

  ENDMETHOD.
ENDCLASS.
