CLASS zcl_31_vat_indicator_alg DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  DATA: vat_ind TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_31_VAT_INDICATOR_ALG IMPLEMENTATION.
ENDCLASS.
