CLASS zcl_21_airplane_alg DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS airplane_type ABSTRACT RETURNING VALUE(rv_airplane_type) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_21_AIRPLANE_ALG IMPLEMENTATION.
ENDCLASS.
