CLASS zcl_10_eu_citizen_alg DEFINITION INHERITING FROM zcl_09_citizen_alg
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_10_EU_CITIZEN_ALG IMPLEMENTATION.
ENDCLASS.
