CLASS zcl_18_moto_alg DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS set_hp IMPORTING iv_hp TYPE i.

  PROTECTED SECTION.
    METHODS set_max_speed ABSTRACT IMPORTING iv_max_speed TYPE i.

  PRIVATE SECTION.
    DATA hp TYPE i.
ENDCLASS.



CLASS ZCL_18_MOTO_ALG IMPLEMENTATION.


  METHOD set_hp.

  ENDMETHOD.
ENDCLASS.
