CLASS zcl_08_lion_alg DEFINITION INHERITING FROM zcl_07_animal_alg
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_08_LION_ALG IMPLEMENTATION.


  METHOD walk.
    rv_walk = 'The lion walks'.
  ENDMETHOD.
ENDCLASS.
