CLASS zcl_06_storage_alg_c367 DEFINITION INHERITING FROM zcl_05_plant_alg_c367
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_06_STORAGE_ALG_C367 IMPLEMENTATION.
ENDCLASS.
