CLASS zcl_29_keyboard_alg DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA keyboard_type TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_29_KEYBOARD_ALG IMPLEMENTATION.
ENDCLASS.
