CLASS zcx_53_exception3_alg DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_53_EXCEPTION3_ALG IMPLEMENTATION.
ENDCLASS.
